apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "WorkingNotebook"
  annotations:
    github.com/project-slug: 'MYSTAKE-ENG/WorkingNotebook'
    backstage.io/techdocs-ref: dir:.
    links:
    - url: https://dashboard.example.com
      title: ADX dashboard with results
      icon: dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  system: stomp
  dependsOn:
    - resource:default/ests
  partOf:
    - domain:default/AntiPhishing
  dependencyOf:
    - service:default/OctoFrog-BrowserIds
