apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "WorkingNotebook"
  annotations:
    github.com/project-slug: 'MYSTAKE-ENG/WorkingNotebook'
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  system: stomp
  dependsOn:
    - resource:default/ests
  partOf:
    - domain:default/AntiPhishing
  dependencyOf:
    - service:default/OctoFrog-BrowserIds
